package com.thediyguide.order.service.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

@DynamoDBTable(tableName = "order-service-orderLineItems")
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class OrderLineItems {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String Id;
    @DynamoDBAttribute
    private String skuCode;
    @DynamoDBAttribute
    private BigDecimal price;
    @DynamoDBAttribute
    private Integer quantity;
}
